{{- if .Values.deployment }}
{{- if .Values.deployment.enabled }}
{{- with .Values.deployment }}
{{- if eq .strategy "canary" }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: {{ $.Release.Name }}
  labels:
    release: {{ $.Release.Name }}
    app: {{ $.Release.Name }}
{{- include "generic-chart.extraMetadataLabels" . | indent 4 }}
spec:
  revisionHistoryLimit: {{ .revisionHistoryLimit }}
  {{- if .replicas }}
  replicas: {{ .replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
{{- include "generic-chart.extraLabels" . | indent 6 }}
  strategy:
    {{- if eq .strategy "RollingUpdate" }}
    rollingUpdate: {{ toYaml .strategySpec | nindent 6 }}
    type: RollingUpdate
    {{- else if eq .strategy "Recreate" }}
    type: Recreate
    {{- else if eq .strategy "canary" }}
    canary: {{ toYaml .strategySpec | nindent 6 }}
    {{- end }}
  template:
    metadata:
      {{- if $.Values.configmap }}
      annotations: 
        checksum: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
      {{- end }}
      labels:
        app: {{ $.Release.Name }}
{{- include "generic-chart.extraLabels" . | indent 8 }}
    spec:
      {{- if .enableServiceLinks }}
      enableServiceLinks: {{ .enableServiceLinks.value }}
      {{- end }}
      {{- if .affinity }}
      affinity: {{ toYaml .affinity | nindent 8 }}
      {{- end }}
      containers:
        {{- range $key,$value := .containers }}
        - image: {{ .image | default $.Values.image }}
          imagePullPolicy: {{ .imagePullPolicy | default $.Values.deployment.imagePullPolicy }}
          name: {{ $key | default $.Release.Name }}
          {{- if .env }}
          env:
{{- include "generic-chart.envvars" . | indent 12 }} 
          {{- end }}
          {{- if .envFrom }}
          envFrom: {{ toYaml .envFrom | nindent 12 }} 
          {{- end }}
          {{- if .command }}
          command: {{ toYaml .command | nindent 12 }}
          {{- end }}
          {{- if .args }}
          args: {{ toYaml .args | nindent 12 }}
          {{- end }}
          {{- if .resources }}
          resources: {{ toYaml .resources | nindent 12 }}
          {{- end }}
          {{- if .ports }}
          ports: {{ toYaml .ports | nindent 10 }}
          {{- end }}
          {{- if .livenessProbe }}
          livenessProbe: {{ toYaml .livenessProbe | nindent 12 }} 
          {{- end }}
          {{- if .readinessProbe }}
          readinessProbe: {{ toYaml .readinessProbe | nindent 12 }} 
          {{- end }}
          {{- if .lifecycle }}
          lifecycle: {{ toYaml .lifecycle | nindent 12 }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts: {{ toYaml .volumeMounts | nindent 12 }}
          {{- end }}
          {{- if .securityContext }}
          securityContext: {{ toYaml .securityContext | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- if .volumes }}
      volumes: {{ toYaml .volumes | nindent 8 }}
      {{- end }}
      {{- if .terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .tolerations }}
      tolerations: {{ toYaml .tolerations | nindent 8 }}
      {{- end }}
      {{- if not (empty .nodeSelector) }}
      nodeSelector: {{ toYaml .nodeSelector | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
